# Generated by Django 4.2.11 on 2024-06-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('game_time', models.DateTimeField(blank=True, null=True)),
                ('live', models.BooleanField(default=False)),
                ('inning', models.CharField(blank=True, max_length=10, null=True)),
                ('state_of_inning', models.CharField(blank=True, max_length=10, null=True)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('balls', models.IntegerField(blank=True, null=True)),
                ('strikes', models.IntegerField(blank=True, null=True)),
                ('outs', models.IntegerField(blank=True, null=True)),
                ('team1_spread', models.CharField(blank=True, max_length=10, null=True)),
                ('team2_spread', models.CharField(blank=True, max_length=10, null=True)),
                ('team1_total', models.CharField(blank=True, max_length=10, null=True)),
                ('team2_total', models.CharField(blank=True, max_length=10, null=True)),
                ('team1_money', models.CharField(blank=True, max_length=10, null=True)),
                ('team2_money', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
