# Generated by Django 4.2.11 on 2024-06-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_game_team1_money_alter_game_team1_spread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state_of_inning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
