# Generated by Django 4.2.11 on 2024-06-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_state_of_inning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='inning',
        ),
        migrations.RemoveField(
            model_name='game',
            name='state_of_inning',
        ),
        migrations.AddField(
            model_name='game',
            name='inning_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
