# Generated by Django 4.2.11 on 2024-06-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_game_inning_remove_game_state_of_inning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='inning_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
