# Generated by Django 4.2.11 on 2024-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mlbgame_mlsgame_nbagame_ncaabaskballgame_ncaabbgame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlsgame',
            name='team1_money',
        ),
        migrations.RemoveField(
            model_name='mlsgame',
            name='team1_score',
        ),
        migrations.RemoveField(
            model_name='mlsgame',
            name='team1_spread',
        ),
        migrations.RemoveField(
            model_name='mlsgame',
            name='team1_total',
        ),
        migrations.RemoveField(
            model_name='mlsgame',
            name='team2_money',
        ),
        migrations.RemoveField(
            model_name='mlsgame',
            name='team2_score',
        ),
        migrations.RemoveField(
            model_name='mlsgame',
            name='team2_spread',
        ),
        migrations.RemoveField(
            model_name='mlsgame',
            name='team2_total',
        ),
        migrations.AddField(
            model_name='mlsgame',
            name='draw_odds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mlsgame',
            name='team1_odds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mlsgame',
            name='team2_odds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
