# Generated by Django 4.2.11 on 2024-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mlsgame_team1_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbgame',
            name='game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mlsgame',
            name='game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nbagame',
            name='game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ncaabaskballgame',
            name='game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ncaabbgame',
            name='game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ncaafbgame',
            name='game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wnbagame',
            name='game_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
