# Generated by Django 4.2.11 on 2024-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mlbspecials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbspecials',
            name='bet_titles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mlbspecials',
            name='odds',
            field=models.TextField(),
        ),
    ]
