# Generated by Django 4.2.11 on 2024-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_mlbspecials_bet_titles_alter_mlbspecials_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBPlayerFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('players', models.TextField()),
                ('odds', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MLBTeamPlayoffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_title', models.CharField(max_length=100)),
                ('yes_odds', models.CharField(blank=True, max_length=20, null=True)),
                ('no_odds', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLBWinTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('over_title', models.CharField(max_length=100)),
                ('under_title', models.CharField(max_length=100)),
                ('over_odds', models.CharField(blank=True, max_length=20, null=True)),
                ('under_odds', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
