# Generated by Django 4.2.11 on 2024-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_wnbafutures_wnbaplayerfutures'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('teams', models.TextField()),
                ('odds', models.TextField()),
            ],
        ),
    ]
