# Generated by Django 4.2.11 on 2024-06-13 16:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mlsfutures'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCAABBFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('teams', models.TextField()),
                ('odds', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NFLDivisionSpecials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('bet_titles', models.TextField()),
                ('odds', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NFLFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('teams', models.TextField()),
                ('odds', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NFLPlayerFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('players', models.TextField()),
                ('odds', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NFLPlayerTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_title', models.CharField(max_length=100)),
                ('over_decimal_odds', models.CharField(blank=True, max_length=20, null=True)),
                ('under_decimal_odds', models.CharField(blank=True, max_length=20, null=True)),
                ('over_american_odds', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFLSeasonSpecials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('teams', models.TextField()),
                ('odds', models.TextField()),
            ],
        ),
    ]
