# Generated by Django 4.2.11 on 2024-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_nfldivisionspecials_teams_titles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBGameLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField()),
            ],
        ),
    ]
