# Generated by Django 4.2.11 on 2024-06-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_mlbgamelinks_nflplayertotals_under_american_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBGameParlays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('player', models.CharField(blank=True, max_length=50, null=True)),
                ('decimal_odds', models.TextField()),
                ('american_odds', models.TextField()),
            ],
        ),
    ]
