# Generated by Django 4.2.11 on 2024-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_mlbgameparlays_nflplayertotals_under_american_odds'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgameparlays',
            name='game',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
