# Generated by Django 4.2.11 on 2024-06-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_mlbgameparlays_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBGameProps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(blank=True, max_length=100, null=True)),
                ('section_title', models.CharField(max_length=100)),
                ('row_title', models.CharField(max_length=100)),
                ('decimal_odds', models.TextField()),
                ('american_odds', models.TextField()),
            ],
        ),
    ]
