# Generated by Django 4.2.11 on 2024-06-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_mlbgameprops_nflplayertotals_under_american_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBPlayerProps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.CharField(blank=True, max_length=100, null=True)),
                ('section_title', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=100)),
                ('row_title', models.CharField(max_length=100)),
                ('decimal_odds', models.TextField()),
                ('american_odds', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mlbgameparlays',
            name='game_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mlbgameprops',
            name='game_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
