# Generated by Django 4.2.11 on 2024-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mlbplayerprops_mlbgameparlays_game_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBGameSpecials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.CharField(blank=True, max_length=100, null=True)),
                ('section_title', models.CharField(max_length=100)),
                ('row_value', models.CharField(blank=True, max_length=20, null=True)),
                ('odds', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MLBPlayerProps',
            new_name='MLBGamePlayerProps',
        ),
    ]
