# Generated by Django 4.2.11 on 2024-06-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_mlbgamespecials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('LID', models.CharField(max_length=10)),
                ('LYID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('bias', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MLB_Team',
            fields=[
                ('TID', models.CharField(max_length=10)),
                ('TYID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('LYID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.league')),
            ],
        ),
        migrations.CreateModel(
            name='MLB_Player',
            fields=[
                ('PID', models.CharField(max_length=10)),
                ('PYID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('TYID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mlb_team')),
            ],
        ),
        migrations.CreateModel(
            name='MLB_Game',
            fields=[
                ('GID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('LYID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.league')),
                ('h_TYID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='api.mlb_team')),
                ('v_TYID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='api.mlb_team')),
            ],
        ),
    ]
