# Generated by Django 4.2.11 on 2024-06-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_league_nflplayertotals_under_american_odds_mlb_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlb_player',
            name='LYID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.league'),
        ),
    ]
