# Generated by Django 4.2.11 on 2024-06-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_mlb_player_lyid_nflplayertotals_under_american_odds'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlb_player',
            name='link',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
