# Generated by Django 4.2.11 on 2024-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_mlb_player_link_nflplayertotals_under_american_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlb_player',
            name='PYID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
