# Generated by Django 4.2.11 on 2024-06-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_mlb_player_at_bats_mlb_player_batting_average_and_more'),
    ]

    operations = [
    ]
