# Generated by Django 4.2.11 on 2024-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_nfl_conference_nfl_player_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfl_conference',
            name='CID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
