# Generated by Django 4.2.11 on 2024-06-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_nfl_conference_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfl_conference',
            name='CYID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
