# Generated by Django 4.2.11 on 2024-06-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_nfl_conference_nfl_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfl_division',
            name='first_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_place_in_conference', to='api.nfl_team'),
        ),
        migrations.AlterField(
            model_name='nfl_division',
            name='fourth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_place_in_conference', to='api.nfl_team'),
        ),
        migrations.AlterField(
            model_name='nfl_division',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_place_in_conference', to='api.nfl_team'),
        ),
        migrations.AlterField(
            model_name='nfl_division',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place_in_conference', to='api.nfl_team'),
        ),
    ]
