# Generated by Django 4.2.11 on 2024-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_nflplayertotals_under_american_odds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlb_player',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
