# Generated by Django 4.2.11 on 2024-06-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_nflplayertotals_under_american_odds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfl_player',
            old_name='games',
            new_name='games_played',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='games_started',
        ),
    ]
