# Generated by Django 4.2.11 on 2024-06-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_games_nfl_player_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfl_player',
            name='extra_point_percetage',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='field_goal_attempts',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='field_goals_made',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='fumbles_recovered',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='interception_percentage',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='kick_fair_catches',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='kick_return_attempts',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='kick_return_average',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='kick_return_touchdowns',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='kick_return_yards',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='passing_touchdown_percentage',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='punt_fair_catches',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='punt_return_attempts',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='punt_return_average',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='punt_return_touchdowns',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='punt_return_yards',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='receiving_yards_per_game',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='rushing_yards_per_game',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='twenty_plus_yard_receptions',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='yards_after_catch',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='yards_lost',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='yards_per_game',
        ),
        migrations.AddField(
            model_name='nfl_player',
            name='field_goal_ratio',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='nfl_player',
            name='receiver_fumbles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_player',
            name='receiver_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
