# Generated by Django 4.2.11 on 2024-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_nfl_team_qb_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfl_team',
            name='o_yards_per_game',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_team',
            name='yards_per_game',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nflplayertotals',
            name='under_american_odds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
