# Generated by Django 4.2.11 on 2024-07-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_nfl_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfl_game',
            name='qb',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='qb_passing_touchdowns',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='qb_passing_yards',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='qb_team',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='rb',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='rb_carries',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='rb_rushing_touchdowns',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='rb_rushing_yards',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='rb_team',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='wr',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='wr_receiving_touchdowns',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='wr_receiving_yards',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='wr_receptions',
        ),
        migrations.RemoveField(
            model_name='nfl_game',
            name='wr_team',
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_qb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_qb', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_qb_interceptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_qb_passing_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_qb_passing_completions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_qb_passing_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_qb_passing_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_qb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_rb_1', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_1_carries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_1_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_1_rush_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_1_rush_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_1_rushing_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_1_rushing_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_rb_2', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_2_carries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_2_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_2_rush_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_2_rush_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_2_rushing_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_rb_2_rushing_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_team', to='api.nfl_team'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_wr_1', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_1_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_1_receiving_targets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_1_receiving_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_1_receiving_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_1_reception_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_1_reception_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_1_receptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_wr_2', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_2_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_2_receiving_targets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_2_receiving_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_2_receiving_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_2_reception_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_2_reception_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='h_wr_2_receptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_qb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_qb', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_qb_interceptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_qb_passing_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_qb_passing_completions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_qb_passing_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_qb_passing_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_qb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_rb_1', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_1_carries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_1_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_1_rush_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_1_rush_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_1_rushing_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_1_rushing_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_rb_2', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_2_carries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_2_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_2_rush_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_2_rush_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_2_rushing_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_rb_2_rushing_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_team', to='api.nfl_team'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_wr_1', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_1_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_1_receiving_targets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_1_receiving_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_1_receiving_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_1_reception_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_1_reception_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_1_receptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_wr_2', to='api.nfl_player'),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_2_fumbles_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_2_receiving_targets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_2_receiving_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_2_receiving_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_2_reception_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_2_reception_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfl_game',
            name='v_wr_2_receptions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
