# Generated by Django 4.2.11 on 2024-07-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_nfl_game_h_qb_name_nfl_game_h_rb_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfl_game',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
