# Generated by Django 4.2.11 on 2024-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_nfl_game_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLB_Game_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
