name: Deploy React App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.2' # Update this to match the Node.js version you're using locally

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: frontend-web/kobralocks

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./build
        working-directory: frontend-web/kobralocks

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: frontend-web/kobralocks/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: release-artifact

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8764E8D9215348C99B5883A3CEB559B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_066250B9527D41A285684C409EBB0FDB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_34A7E0934C6541B1B898EDB48474F3E6 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'KobraLocksFrontEnd'
          package: .
