name: Deploy React App to Azure
on: [push]

env:
  AZURE_WEBAPP_NAME: KobraLocksFrontEnd   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './frontend-mobile/kobralocks/'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
   
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8764E8D9215348C99B5883A3CEB559B4 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_066250B9527D41A285684C409EBB0FDB }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_34A7E0934C6541B1B898EDB48474F3E6 }}
        
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory:  ./frontend-web/kobralocks/
               
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./build

    # Azure logout 
    - name: logout
      run: |
        az logout

